#cloud-config

package_update: true
package_upgrade: true

packages: [git, jq, python3-pip]

fs_setup:
  - device: /dev/sdb
    filesystem: ext4
    partition: none

mounts:
  - [sdb, /mnt/data-volume, auto, defaults]

runcmd:
  - mkdir -p /root/.config/scw

  - |
    access_key=$(scw-userdata scw-access-key)
    secret_key=$(scw-userdata scw-secret-key)

    metadata=$(scw-metadata-json)

    organization=$(echo "$metadata" | jq -r '.organization')
    project=$(echo "$metadata" | jq -r '.project')
    zone=$(echo "$metadata" | jq -r '.zone')
    region=${zone::-2}

    cat > /root/.config/scw/config.yaml <<EOF
    access_key: $access_key
    secret_key: $secret_key
    default_organization_id: $organization
    default_project_id: $project
    default_region: $region
    default_zone: $zone
    api_url: https://api.scaleway.com
    EOF

  - chmod 600 /root/.config/scw/config.yaml

ansible:
  package_name: ansible-core
  install_method: distro
  galaxy:
    actions:
      - command: install
        args:
          - scaleway.scaleway
  pull:
    - url: https://github.com/tlsquared/forge-ansible.git
