[tools]
opentofu = "1.11"

[env]
SCW_ACCESS_KEY = { required = true, redact = true }
SCW_SECRET_KEY = { required = true, redact = true }

[tasks.init]
run = "tofu -chdir=terraform init -reconfigure"
env = {
    AWS_ACCESS_KEY_ID = "{{ env.SCW_ACCESS_KEY }}",
    AWS_SECRET_ACCESS_KEY = "{{ env.SCW_SECRET_KEY }}"
}

[tasks.plan]
run = "tofu -chdir=terraform plan"
env = {
    AWS_ACCESS_KEY_ID = "{{ env.SCW_ACCESS_KEY }}",
    AWS_SECRET_ACCESS_KEY = "{{ env.SCW_SECRET_KEY }}"
}

[tasks.apply]
run = "tofu -chdir=terraform apply"
env = {
    AWS_ACCESS_KEY_ID = "{{ env.SCW_ACCESS_KEY }}",
    AWS_SECRET_ACCESS_KEY = "{{ env.SCW_SECRET_KEY }}"
}
